# Generated by Django 6.1.1 on 2026-09-22 15:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('version', models.CharField(default='1.0.0', max_length=32)),
                ('algorithm', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(help_text='Path to the .joblib/.pkl artifact on disk.', max_length=512)),
                ('metrics', models.JSONField(blank=True, help_text='Stored evaluation metrics (accuracy, F1, etc.).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('asset_type', models.CharField(choices=[('SERVER', 'Server'), ('WORKSTATION', 'Workstation'), ('NETWORK_DEVICE', 'Network Device'), ('DATABASE', 'Database'), ('CLOUD', 'Cloud Resource'), ('IOT', 'IoT Device'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('criticality', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('MISSION_CRITICAL', 'Mission Critical')], default='MEDIUM', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('operating_system', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criticality', 'name'],
                'indexes': [models.Index(fields=['asset_type'], name='security_as_asset_t_0aa749_idx'), models.Index(fields=['criticality'], name='security_as_critica_977150_idx'), models.Index(fields=['is_active'], name='security_as_is_acti_0bac82_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('FIREWALL', 'Firewall'), ('IDS', 'Intrusion Detection System'), ('ENDPOINT', 'Endpoint'), ('SERVER', 'Server'), ('AUTH', 'Authentication'), ('APPLICATION', 'Application'), ('NETWORK', 'Network'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=128)),
                ('message', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='security.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('score', models.FloatField(blank=True, help_text='Confidence or anomaly score.', null=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='security.logentry')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='security.mlmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('MALWARE', 'Malware'), ('PHISHING', 'Phishing'), ('RANSOMWARE', 'Ransomware'), ('DDOS', 'DDoS'), ('INSIDER', 'Insider Threat'), ('APT', 'Advanced Persistent Threat'), ('VULN_EXPLOIT', 'Vulnerability Exploit'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('indicators', models.TextField(blank=True, help_text='IOCs, signatures, or detection hints (free text).')),
                ('mitre_technique', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-severity', 'name'],
                'indexes': [models.Index(fields=['category'], name='security_th_categor_918193_idx'), models.Index(fields=['severity'], name='security_th_severit_825832_idx')],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('CONTAINED', 'Contained'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('FALSE_POSITIVE', 'False Positive')], default='OPEN', max_length=32)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='security.asset')),
                ('threat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='security.threat')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('is_patched', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='security.asset')),
            ],
            options={
                'ordering': ['-cvss_score', '-discovered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['source'], name='security_lo_source_558873_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['is_processed'], name='security_lo_is_proc_a4c632_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['label'], name='security_pr_label_63a787_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['is_anomaly'], name='security_pr_is_anom_d7f388_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='security_in_status_83d382_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity'], name='security_in_severit_f49377_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['detected_at'], name='security_in_detecte_f3058b_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['severity'], name='security_vu_severit_13f2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['is_patched'], name='security_vu_is_patc_ffee7b_idx'),
        ),
    ]
